### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by stl1988** [lnbits/bitcoinswitch#6]
When compiling, it shows the error as seen on the screenshot.

![FifBg6ZXgAE3pLa](https://user-images.githubusercontent.com/35177539/204208497-48139a05-6c9b-414c-87e1-84d3786380bd.jpeg)

**Comment by stl1988** [comment]
I posted this on Twitter first before issues on this fork were a thing.

**Comment by dni** [comment]
is this still relevant?

**Comment by dni** [comment]
should be fixed by now
